version: '3.8'
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 80
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    ports:
      - 3000:3000
